### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by root1991** [dmytroKarataiev/YalantisInternship#2]
Error:(80, 28) No resource found that matches the given name (at 'value' with value '@string/google_maps_key').

**Comment by dmytroKarataiev** [comment]
Solved earlier by [commit](https://github.com/dmytroKarataiev/YalantisInternship/commit/570c81a688c93d3c78d3cfe60e464bf9dc64f1cc).

Also, as per readme, google maps key must be placed in a google_maps_api.xml file as a string.
